FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install flask psycopg2-binary
# Caso crie requirements.txt, substitua o comando acima por:
# RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "main.py"]