version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc-rfp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mvc-rfp-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mvc_rfp
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: mvc-rfp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvc_rfp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
